# Code generated by chatgpt when asked: 
# "How can you use R for machine learning?"

# load caret package
library(caret)

# load dataset
data(iris)

# split the data into training and test sets
set.seed(123)
train_ind <- createDataPartition(iris$Species, p = 0.8, list = FALSE)
train <- iris[train_ind,]
test <- iris[-train_ind,]

# train a decision tree model
model <- train(Species ~ ., data = train, method = "rpart")

# make predictions on test set
predictions <- predict(model, newdata = test)

# evaluate model performance
confusionMatrix(predictions, test$Species)
