# Code generated by chatgpt when asked: 
# "How do you plot a  graph in R?"

# Line plot
x <- c(1, 2, 3, 4)
y <- c(10, 20, 30, 40)
plot(x, y)

# Scatter plot
library(ggplot2)
data <- data.frame(x=c(1, 2, 3, 4), y=c(10, 20, 30, 40))
ggplot(data, aes(x, y)) + geom_point()
