# Code generated by chatgpt when asked: 
# "Can you give me another example using the randomForest package?"
# This also displays how chatgpt can build off of previous
# answers it has given you as it is building off of the 
# ml_example.R example!

# load randomForest package
library(randomForest)

# load dataset
data(iris)

# split the data into training and test sets
set.seed(123)
train_ind <- createDataPartition(iris$Species, p = 0.8, list = FALSE)
train <- iris[train_ind,]
test <- iris[-train_ind,]

# train a random forest model
model <- randomForest(Species ~ ., data = train, ntree = 500)

# make predictions on test set
predictions <- predict(model, newdata = test)

# evaluate model performance
confusionMatrix(predictions, test$Species)
